rails_app/config/routes.rb
Wepoll::Application.routes.draw do
  resources :timeline_entries do
    get 'blame', :on => :member
    get 'like', :on => :member
    get 'entry', :on => :member
  end

  resources :messages do 
		match '/list' => 'messages#list', :as => "list"
    post 'message_replies' => 'message_replies#create', :as => :replies
    get 'message_replies' => 'message_replies#index', :as => :replies
    get 'blame', :on => :member
    get 'like', :on => :member
  end

  resources :message_replies, :only => [:destroy]
  match "link_counts/:id" => "politicians#link_counts", :as => :link_counts_of_politician, :constraints => {:id => /[a-z0-9]+/}
  match "link_counts/:district" => "politicians#link_counts", :as => :link_counts_of_politician
  match 'timeline/:timeline_entry_id' => 'district#show_timeline_entry', :via => :get, :as => :display_timeline_entry
#  match "timeline_entries/list/:id" => "timeline_entries#list", :as => "timeline_entries_list"

  resources :bills
  resources :link_replies do
    match "/list" => "link_replies#list", :as => "list"
    get 'blame', :on => :member
    get 'like', :on => :member
  end
  resources :notices

  namespace :admin do
    match '/' => 'admin#index'
    match 'login' => 'auth#login'
    match 'logout' => 'auth#logout'
    match 'authorize' => 'auth#authorize'
    match 'new' => 'admin#new_admin', :via => :get
    match 'create' => 'admin#create_admin', :via => :post
    resources 'politicians' do
      get 'search', :as => 'search', :on => :collection
      post 'upload_photo', :as => 'upload_photo', :on => :collection
      get 'crawl_init_bills', :as => 'crawl_initiate_bill', :on => :member
    end
    resources 'bills' do
      get 'search', :as => 'search', :on => :collection
    end

    resources 'timeline_entries'
    resources 'users' do
      get 'suspend', :as => 'suspend', :on => :member
      post 'suspend_confirm', :as => 'suspend_confirm', :on => :member
      post 'suspend_cancel', :as => 'suspend_cancel', :on => :member
    end

    resources 'notices'
    resources 'link_replies'
    resources 'tweet_replies'
    resources 'tweets'
    resources 'pledges' do
      get 'search', :as => 'search', :on => :collection
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :sessions => "users/sessions"} do
    match 'users/sign_up/link_sns/:id' => 'users/registrations#link_sns', :via => :get, :as => 'new_user_link_sns'
    match '/auth_completed' => 'users/registrations#after_auth', :as => :after_auth
  end

  match 'users/auth/twitter/callback' => 'users/omniauth_callbacks#twitter'


  namespace :me do
    match 'sns/' => "sns#index"
    match 'sns/link/:provider' => "sns#link", :as => :sns_link
    match 'sns/mail_fail' => 'sns#mail_resend', :as => :sns_mail_resend

    match '/' => 'dashboard#index', :as => "dashboard"
  end
  match '/sns_verify/:user_id/:token_id/:key' => 'me/sns#verify_sns_link',
    :via => :get, :as => :sns_link_verify

  get 'forum/:tweet_name' => 'tweets#forum' , :as => :forum
  match '/get_tweet/:screen_name' => 'tweets#get_tweet', :as => :get_tweet

  resources :tweets do
    get 'like', :on => :member
    post 'tweet_replies' => 'tweet_replies#create', :as => :tweet_replies
    get 'tweet_replies' => 'tweet_replies#index', :as => :tweet_replies
  end
  resources :tweet_replies do
    get 'blame', :on => :member
    get 'like', :on => :member
    delete 'destroy', :on => :member
  end

  resources :pledges do
    get 'like', :on => :member, :as => :like
    get 'dislike', :on => :member, :as => :dislike
  end

  match '/fb_post_callback' => 'tweet_replies#fb_post_callback', :as => :fb_post_callback

  match 'district/:name/:p1_id/:p2_id' => 'district#show' ,:constraints => {:p1_id => /[a-z0-9]+/, :p2_id => /[a-z0-9]+/}, :as => :district_vs_politicians
  match 'district/:politician_id' => 'district#show' ,:constraints => {:politician_id => /[a-z0-9]+/}, :as => :district_politician
  match 'district/:name' => "district#show", :as => :district_name

  resources :politicians do
    get 'initiate_bills', :on => :member, :as => :init_bills_by
    get 'initiate_bills_summary',:on => :member, :as => :init_bills_summary_of
    get 'top_joint_initiate_bills',:on => :member, :as => :top_joint_initiate_bills_of
    get 'bill_activities', :on => :collection, :as => :bill_activities_of

    get 'popular_links', :on => :member, :as => :popular_links_of
    get 'recent_links', :on => :member, :as => :recent_links_of

    get 'popular_links_tab', :on => :collection, :as => :popular_links_tab_of
    get 'recent_links_tab', :on => :collection, :as => :recent_links_tab_of
    get 'votes_for_issues_tab', :on => :collection, :as => :votes_for_issues_tab_of

    get 'profile', :on => :collection, :as => :profiles_of
    get 'pledges', :on => :collection, :as => :pledges_of
    get 'messages_tab', :on => :collection, :as => :messages_tab_of

    get 'messages', :on => :collection, :as => :messages_of
  end

  match "/search" => "main#search"
match '/provision' => 'main#provision'
match '/privacy' => 'main#privacy'

  root :to => 'main#index'


  #for test
  match 'main/fb_test' => 'main#facebook_test', :as => :fb_test
  match 'main/fb_test_callback' => 'main#facebook_test_callback', :as => :fb_test_callback

  match 'main/tw_test' => 'main#twitter_test', :as => :tw_test
  match 'api/article_parse' => 'api#article_parsing'
  match 'api/youtube_parse' => 'api#youtube_parsing'
end

rails_app/app/controllers/district_controller.rb
#coding:utf-8
require 'iconv'
class DistrictController < ApplicationController
  before_filter :simplify_district_name
  before_filter :ready_politicians, :except => [:show_timeline_entry]
  def show
    respond_to do |format|
      format.html do
        #timeline bootstrap
        # Timeline => See timeline_controller.rb.
        if params[:from]
          q_time = {:updated_at => {'$gte' => params[:from]}}
        elsif params[:after]
          q_time = {:updated_at => {'$gt' => params[:after]}}
        else
          q_time = {:deleted => false} # (all except deleted)
        end
        @timeline_entries = TimelineEntry.where(q_time).where(:politician_id.in => [@p1,@p2].map {|p| p.nil? ? nil : p.id})
        @message = Message.new
        @messages = Message.where(:district => @district).desc("created_at").page(params[:page]).per(10)
        @best_message = Message.where(:district => @district).desc('like_count').first
        @bills = Bill.limit(20)
        @vote_exists = !VoteForBillByPolitician.where(:politician_id.in => [@p1.id,@p2.id]).first.nil?
      end
      format.js {render :json => Politician.where(district: @district, candidate: 1).sort {|x,y| x.number <=> y.number }, :only => [:name, :party, :_id, :number]}
    end
  end

  def show_timeline_entry
    @message = Message.new
    @messages = Message.where(:district => @district).desc("created_at").page(params[:page]).per(10)
    @best_message = Message.where(:district => @district).desc('like_count').first
    @politicians = Politician.where(:district => @district).where(:candidate => true).sort {|x,y| (y.good_link_count + y.bad_link_count) <=> (x.good_link_count + x.bad_link_count)}
    @party_color = {"자유선진" => "#007DC5", "통합진보" => "#6F0086", "무소속" =>"#4F4F50","진보신당" => "#f5314f", "민주통합" => "#257a01", "새누리당" => "#c2271e" }
    @timeline_entry = TimelineEntry.find(params[:timeline_entry_id])
    @p1 = @timeline_entry.politician
    @p2 = Politician.where(:district => @p1.district).reject {|p| p.id == @p1.id}.first
    p1_bill_categories = @p1.nil? ? [] : @p1.initiate_bills_categories((params[:age]||18).to_i)
    p2_bill_categories = @p2.nil? ? [] : @p2.initiate_bills_categories((params[:age]||18).to_i)

    @p1_bill_counts = p1_bill_categories.map {|c,n| n}
    @p1_bill_categories = p1_bill_categories.map {|c,n| c}

    @p2_bill_counts = p2_bill_categories.map {|c,n| n}
    @p2_bill_categories = p2_bill_categories.map {|c,n| c}

    @other_politicians = @politicians.reject {|p| p == @p1 || p==@p2}

    @t1 = @p1.nil? ? nil : @p1.tweets.desc('created_at').first
    @t2 = @p2.nil? ? nil : @p2.tweets.desc('created_at').first
    @tweets = [@t1, @t2]

    render :action => 'show'
  end

  protected
  def simplify_district_name
    Rails.logger.info "simplify_district_name"
    if !params[:name].nil?
      #      if request.env["HTTP_USER_AGENT"] =~ /MSIE/
      #	iconv = Iconv.new("UTF-8//IGNORE", "EUC-KR")
      begin
        params[:name] = params[:name].encode("UTF-8")
      rescue
      end
      #      end
      str = params[:name]
      redirect_to root_url if str == "undefined"
      if str && (%w(구 시).include? str[-2]) && (%w(갑 을 병 정 무 기 경 신 임 계).include? str[-1])
        if str.length-2 >= 2
          str = str[0...-2]+str[-1]
        end
      end
      @district = str
    elsif !params[:politician_id].nil?
      str = params[:politician_id].to_s
      if str == "undefined"
        redirect_to root_url
      else
        @p1 = Politician.find(str)
        @district = @p1.district
        redirect_to root_url if @district.empty?
      end
    elsif !params[:timeline_entry_id].nil?
      timeline_entry = TimelineEntry.find(params[:timeline_entry_id])
      @district = timeline_entry.politician.district
    end
  end

  def ready_politicians
    Rails.logger.info "district = " +@district
    @politicians = Politician.where(:district => @district).where(:candidate => true).sort {|x,y| y.message_count <=> x.message_count}
    @party_color = {"자유선진" => "#007DC5", "통합진보" => "#6F0086", "무소속" =>"#4F4F50","진보신당" => "#f5314f", "민주통합" => "#257a01", "새누리당" => "#c2271e" }
    if @politicians.count == 1
      @p1 = @politicians.first
    else
      if (params[:p1_id] && params[:p2_id])
        @p1 = @politicians.find {|p| p.id.to_s == params[:p1_id]}
        @p2 = @politicians.find {|p| p.id.to_s == params[:p2_id]}
      else
        if @p1.nil?
          @p1 = @politicians[0]
          @p2 = @politicians[1]
        else
          if @p1.id == @politicians[0].id
            @p2 = @politicians[1]
          else
            @p2 = @politicians[0]
          end
        end
      end
    end
    redirect_to district_politician_path(:politician_id => @p1.id) if @p1 == @p2

    p1_bill_categories = @p1.nil? ? [] : @p1.initiate_bills_categories((params[:age] || 18).to_i)
    p2_bill_categories = @p2.nil? ? [] : @p2.initiate_bills_categories((params[:age] || 18).to_i)

    @p1_bill_counts = p1_bill_categories.map {|c,n| n}
    @p1_bill_categories = p1_bill_categories.map {|c,n| c}

    @p2_bill_counts = p2_bill_categories.map {|c,n| n}
    @p2_bill_categories = p2_bill_categories.map {|c,n| c}

    @other_politicians = @politicians.reject {|p| p == @p1 || p==@p2}

  end
end

rails_app/app/helpers/district_helper.rb
module DistrictHelper
end

rails_app/app/views/district/_message_form.html.erb
<div class="write-message-area">
  <%= form_for(@message, :remote => true, :html =>{:class => 'link-form message-form'}) do |f| %>
    <%= f.hidden_field :preview_id %>
    <%= f.hidden_field :district, :value => @district %>

    <div id="message-form-politicians" class="clearfix">
      <div id="district-box">
        <span><%= @district %></span><br />
        후보
      </div>
      <div id="politicians-box">
        <div class="radio-politician">
          <%= f.label 'politician_id_all', image_tag("btn_wepoll.gif"), :class => "img-label clearfix" %>
          <%= f.radio_button :politician_id, 'all', :checked => true %>
          <%= f.label 'politician_id_all', '전체', :class => "txt-label" %>
        </div>
        <% @politicians.each do |p| -%>
          <div class="radio-politician">
            <%= f.label 'politician_id_'+p.id.to_s, image_tag(p.profile_photo.url(:square100), :size => "50x50"), :class => "img-label clearfix" %>
            <%= f.radio_button :politician_id, p.id %>
            <%= f.label 'politician_id_'+p.id.to_s, p.name, :class => "txt-label" %>
          </div>
        <% end -%>
      </div>
    </div>

    <div id="message-body-container">
      <% if user_signed_in? -%>
        <%= f.text_area :body, :class => 'comment', :maxlength => 250, :placeholder => "원하는 후보에게 한마디 남겨주세요." %>
      <% else -%>
        <%= f.text_area :body, :class => 'comment', :maxlength => 250, :placeholder => "원하는 후보에게 한마디 남겨주세요.", :onclick => "show_login(); return false;" %>
      <% end -%>
      <div id="message-length-indicator"><span id="message-body-length">00</span>/250</div>
      <div id="message-form-preview" class="preview">
        <img class="preview-img" src="" />
        <div id="message-form-preview-right" class="preview-right">
          <div id="message-form-preview-title" class="preview-title"></div>
          <div id="message-form-preview-link" class="preview-link"></div>
          <div id="message-form-preview-txt" class="preview-txt"></div>
        </div>
      </div>
    </div>
    <% if user_signed_in? -%>
      <%= f.submit '확인', :id => "message-submit-btn" %>
    <% else -%>
      <%= f.submit '확인', :id => "message-submit-btn", :onclick => "show_login(); return false;" %>
    <% end -%>
    <div class="reply_check">
      <span class="checkbox facebook"><input name="message[facebook]" type="checkbox" /></span>
      <span class="checkbox twitter"><input name="message[tweet]" type="checkbox" /></span>
      <span class="note">SNS로 보내기</span>
    </div>
  <% end %>
</div>

<script type="text/javascript">
	$(function(){
		var loaded_url = '';
		$('#message_body').keyup(function(event) {
				var str = $('#message_body').val();
			if (event.keyCode == 32) {
				var regex = /\b([\d\w\.\/\+\-\?\:]*)((ht|f)tp(s|)\:\/\/|[\d\d\d|\d\d]\.[\d\d\d|\d\d]\.|www\.|\.tv|\.ac|\.com|\.edu|\.gov|\.int|\.mil|\.net|\.org|\.biz|\.info|\.name|\.pro|\.museum|\.co)([\d\w\.\/\%\+\-\=\&amp;\?\:\\\&quot;\'\,\|\~\;]*)\b/gi;
				var url = str.match(regex);
				if (url != null && loaded_url != url) {
					loadUrl(url);
					loaded_url = url;
				}
			}

			var $this = $(this);
			var max = 250;
			var len = str.length;
			if (len > max) {
				$('#message_body').val(str.substr(0, max));
				len = $('#message_body').val().length;
			}
			$("#message-body-length").text(len);
		});

	$('#new_message').submit(function() {
		var data_string = $('#new_message').serialize();
		//console.log(data_string);
		$.ajax({
			type: "POST",
			url: "/messages",
			data: data_string
		});
    $('#message_body').val('')
    $.gritter.add({title:"메시지 등록됨",text:"한마디 메시지가 등록되었습니다."})
		return false;

	});
});


	function loadUrl(url)  {
		$.ajax({ url: '/api/article_parse', data: 'url='+encodeURIComponent(url), type: 'POST', dataType: 'json', success: 
			function(data)  { 
				$('#message_preview_id').val(data.id)
				if(data.image)
					$('#message-form-preview img.preview-img').attr('src', data.image);

        $('#message-form-preview-title').html(data.title);
        $('#message-form-preview-link').html(data.url);
				$('#message-form-preview-txt').html(data.description);
				$('#message-body-container .comment').css('border-bottom','none');
        $('#message-form-preview').toggle();
        $('#message-form-preview').css('display', 'block');
			} 
		}); 
	}
</script>

rails_app/app/views/district/_namecard.html.erb
<div class="namecard<%=index==0 ? " alpha" : ""%>">
  <% unless politician.nil? -%>
    <% unless (politician.tweet_name.nil? || politician.tweet_name == "" ) -%>
      <%= link_to forum_path(politician.tweet_name) do  %>
        <div class="tweet-bubble <%= index==0?"left":"right"%>">
          <%= tweet ? (tweet.content.length>100 ? (raw tweet.content[0..100].html_safe)+"..." : (raw tweet.content.html_safe) ) : "최근 트윗이 없습니다." %>
        </div>
      <% end -%>
    <% else -%>
      <div class="tweet-bubble <%= index==0?"left":"right"%>">
        후보의 트위터 아이디가 없습니다.
      </div>
    <% end -%>
  <% else -%>
      <div class="tweet-bubble <%= index==0?"left":"right"%>">
        후보자가 없습니다.
      </div>
  <% end -%>

  <div class="politician-photo-wrapper <%=index==0?"left":"right"%>">
    <%= image_tag politician && politician.profile_photo? ? politician.profile_photo.url(:square160) : "http://placehoold.it/160", :class => "photo" %>
    <div class="photo-frame"></div>
  </div>

  <dl id="<%= "politician#{(index==0 ?  1 : 2)}"%>" class="dropdown <%= index==0?"left":"right"%>">
    <% if politician -%>

    <dt><a><span class="value"><%=politician.id %></span><span class="party" style="color:<%= @party_color[politician.party]||"black" %>"><%= politician.party%></span>&nbsp;<span class="name"><%= politician.name %></span></a></dt>
    <% else -%>
    <dt><a href="javascript:void(0)"><span class="name">후보없음</span></a></dt>
    <% end -%>
    <!--
    <dd>
    <ul>
      <% @politicians.each do |p| -%>
        <% next if p.id == (index==0?(@p2 || @p1) : @p1).id -%>
        <li><a href="#" class="<%= p.id == politician.id ? "current":"" %>" data-id="<%= p.id%>"><span class="value"><%=p.id%></span><span class="party" style="color:<%= @party_color[p.party]||"black" %>"><%= p.party%></span>&nbsp;<span class="name"><%= p.name%></span></a></li>
      <% end -%>
    </ul>
    </dd>
    -->
  </dl>

  <div class="clear"></div>

</div>

rails_app/app/views/district/_top_join_initiate.html.erb
<div class="grid_3 alpha omega">
  <% politician.joint_initiate_bill_politicians[0...3].each_with_index do |tmp, i| -%>
    <div class="grid_1<%= i==0 ? " alpha" : i == 2 ? " omega" : "" %>">
      <% p = Politician.where(:_id => tmp[0]).first -%>
      <% if p && p.profile_photo? -%>
        <%= link_to image_tag(p.profile_photo.url(:square100), :style => "width:48px;height:48px;"), district_politician_path(p.id) %>
      <% else -%>
        <%= link_to image_tag("http://placehold.it/48x48"), '#'%>
      <% end -%>

      <div><%= p.nil? ? tmp[0] : p.name  %></div>
      <div><%= "#{(tmp[1].to_f/politician.initiate_bills.count*100.0).round}%" %></div>
    </div>
  <% end -%>
</div>

rails_app/app/views/district/show.html.erb
<% content_for :scripts do -%>
  <script type="text/javascript">
    var politician_selected_1 = [];
    var attendances = {"<%=@p1.id%>":[<%= @p1.attendance.join(",") %>], "<%=@p2.id%>":[<%=@p2.attendance.join(",")%>]};

    function load_bill_activities(pol_id, age, t) {
      if ($(t).hasClass("selected")) return;

      var $old = $("#age-selector-"+pol_id+" .age-select.selected");
      $old.text(parseInt($old.text()));

      $("#age-selector-" + pol_id+" .age-select").removeClass("selected");
      $(t).addClass("selected");
      $(t).text($(t).text() + "대 국회");

      $("#init-bills-"+pol_id).html('<%= image_tag "/assets/ajax-loader-link.gif" %>');
      $("#joint-initiate-bills-"+pol_id).html('<%= image_tag "/assets/ajax-loader-link.gif" %>');

      $("#init-bills-"+pol_id).load("/politicians/"+pol_id+"/initiate_bills_summary?age="+age);
      $("#joint-initiate-"+pol_id).load("/politicians/"+pol_id+"/top_joint_initiate_bills?age="+age);
      var att = attendances[pol_id][age];
      if (att)
        att = att +"%";
      else
        att = '<span style="font-size:12pt">정보없음</span>';

      $("#attendance-"+pol_id).html(att);
    }

    function law_title_click($elem, id) {
      //show box
      var $div = $("#bill-summary-popup");
      var index = $elem.index();
      if ($div.length == 0) {
        $div = $("<div id=\"bill-summary-popup\"><div id=\"summary-popup-content\"></div>");
        var $a = $("<a id=\"bill-popup-close\" href=\"#\">x</a>");
        $a.click(function() {
          $div.slideUp();
          return false;
        });
        $div.append($a);
        $div.appendTo("#bills-wrapper");
        $div.hide();
      }

      //slide
      $div.stop().slideDown();

      //load html
      $.get("/bills/"+ id, {}, function(data) {
        $("#summary-popup-content").html(data);
        $.colorbox.resize();
      }, "html"); 
      return false;
    }

    $(function() {
      $('span.checkbox').addClass("unchecked");
      $(".checkbox").click(function(){
        if($(this).children("input").attr("checked")){
          // uncheck
          $(this).children("input").removeAttr("checked");
          $(this).removeClass("checked");
          $(this).addClass("unchecked");
        }else{
          // check
          $(this).children("input").attr({checked: "checked"});
          $(this).removeClass("unchecked");
          $(this).addClass("checked");
        }
      });
      var waypoint_opts = {
        offset: '100%'
      };

      //waypoint
      var $politician_bill_activities = $("#politician-bill-activities");
      $politician_bill_activities.waypoint(function(event, direction) {
        if (direction == 'up') return;
        $politician_bill_activities.waypoint('remove');

        var taburl = "<%= bill_activities_of_politicians_path(:id1 => @p1.nil? ? nil : @p1.id, :id2 => @p2.nil? ? nil : @p2.id)%>";
        $politician_bill_activities.load(taburl);
      }, waypoint_opts);

      var $profiles = $("#profiles");
      $profiles.waypoint(function(event, direction) {
        if (direction == 'up') return;
        $profiles.waypoint('remove');
        var taburl = "<%= profiles_of_politicians_path(:id1 => @p1.nil? ? nil : @p1.id, :id2 => @p2.nil? ? nil : @p2.id) %>";
        $profiles.load(taburl);
      }, waypoint_opts);

      var $pledges = $("#pledges");
      $pledges.waypoint(function(event, direction) {
        if (direction == 'up') return;
        $pledges.waypoint('remove');
        var taburl = "<%= pledges_of_politicians_path(:id1 => @p1.nil? ? nil : @p1.id, :id2 => @p2.nil? ? nil : @p2.id) %>";
        $pledges.load(taburl);
      }, waypoint_opts);

      var $politician_vote_activities = $("#politician-vote-activities");
      $politician_vote_activities.waypoint(function(event, direction) {
        if (direction == 'up') return;
        $politician_vote_activities.waypoint('remove');

        var taburl = "<%= votes_for_issues_tab_of_politicians_path(:id1 => @p1.nil? ? nil : @p1.id, :id2 => @p2.nil? ? nil : @p2.id)%>";
        $politician_vote_activities.load(taburl);
      }, waypoint_opts);
    });
  </script>
<% end -%>
<script type="text/javascript">
  /// tooltip
$(document).ready(function() {
  $('.tooltip-top').qtip({position:{my:'bottom center',at:'top center'},style: {classes: 'ui-tooltip-dark'}});
  $('.tooltip-bottom').qtip({position:{my:'top center',at:'bottom center'},style: {classes: 'ui-tooltip-dark'}});

  $('.district-candidate').each( function(index, element) {
    var dropdown;

    $(element).mouseenter(function() {
      dropdown = $(element).children(".candidate-dropdown")
      var pos = $(element).position();
      var w = $(element).outerWidth();
      var h = $(element).outerHeight();
      dropdown.css({left:pos.left + 'px', top: pos.top+ h + 'px', width:w + 20 +'px'})
      //dropdown.show()

    });
    $(element).mouseleave(function() {
      if(dropdown)  {
        dropdown.hide();
      }
    });
  });
});
</script>

<div class="grid_12" id="vs-content-wrapper" style="margin-bottom: 40px;">
  <div id="district-title">
    이 공간은 <span id="district-label"><%= @district %></span> 대결 페이지입니다.
    <fb:like class="fb-like" href="<%= request.url %>" width="100" show_faces="false" layout="button_count" />
  </div>

  <!-- 후보 선택 체크박스 -->
  <div id="district-candidates" class="clearfix">
    <div style="margin-bottom:10px;"><%= @district%>의 후보들을 비교해보세요</div>
    <% @politicians.each do |politician|
      #next if politician.id == @p1.id || politician.id == @p2.id -%>
      <div class="district-candidate">
        <a href="javascript:void(0)" class="district-candidate-button clearfix" title="<%= politician.name %>" style="cursor:default">
          <%= image_tag politician.profile_photo.url(:square100), :class=>"candidate-photo" %>
          <div class="candidate-name">
            <span class="party" style="color:<%=@party_color[politician.party] || "black" %>"><%= politician.party %></span>
            <span class="name" style="font-weight:bold"><%=politician.name %></span>
          </div>
        </a>
        <div class="candidate-checkbox-wrap"><span><input type="checkbox" class="candidate-checkbox" name="selected-candidates" value="<%=politician.id%>"/></span></div>
        <div class="candidate-dropdown">
          <a href="/district/<%=@district%>/<%=politician.id%>/<%=@p2.id%>"><p class='dropdown-item'><span class="target"><%=  politician.name %></span> <span class="vs">VS</span> <%=@p2.name%></p></a>
          <a href="/district/<%=@district%>/<%=@p1.id%>/<%=politician.id%>"><p class='dropdown-item'><%=@p1.name%> <span class="vs">VS</span> <span class="target"><%=  politician.name %></span></p></a>
        </div>
      </div>
    <% end -%>
  </div>
  <script type="text/javascript">

    // activate user friendly UI on candidate list
    $(document).ready(function(){

      function enter(event){
        $(event.currentTarget).addClass('hover')
      }

      function leave(event){
        $(event.currentTarget).removeClass('hover')
      }

      // initially check/uncheck candidate list
      $(".candidate-checkbox").each(function(index,checkbox) {
        if($(checkbox).val() == '<%=@p1.id%>' || $(checkbox).val() =='<%=@p2.id%>')
          $(checkbox).attr('checked', 'checked')
        else
          $(checkbox).removeAttr('checked')
      })


      $(".candidate-checkbox").click(function() {
        var theCheckbox = this;
        var numSelected = 0;
        $(".candidate-checkbox").each(function(index,checkbox){
          if($(checkbox).attr('checked'))
            numSelected ++;
        })

        if(numSelected > 2)  {
          $(".candidate-checkbox").each(function(index,checkbox){
            if(checkbox != theCheckbox)
              $(checkbox).removeAttr('checked')
          })
        }
        else if(numSelected == 2)  {
          var checked = []
          $(".candidate-checkbox").each(function(index,checkbox){
            if($(checkbox).attr('checked'))
              checked.push($(checkbox).val())
          })

          window.location = "/district/" + encodeURIComponent("<%=@district%>") + "/" + checked[0] + "/" + checked[1]
        }


      })

      $(".district-candidate-button").hover(enter,leave)

    })
  </script>

  <!-- 후보 얼굴 및 이름 -->
  <div id="name-cards" class="clearfix">
    <% [@p1, @p2].each_with_index do |politician,i| -%>
      <%= render :partial => 'namecard', :locals => {:politician => politician, :index => i, :tweet => politician.tweets.desc('created_at').first} %>
      <% if i==0 -%>
        <div id="split-bar">
        </div>
      <% end -%>
    <% end -%>
  </div>

  <% unless @best_message.nil? -%>
    <div id="best-message">
      <h1 class="best-label">베스트 한마디</h1>
      <%= render @best_message%>
    </div>
  <% end -%>

  <h1 class="section-label">프로필</h1>
  <div id="profiles" class="section">
  </div>

  <h1 class="section-label">공약</h1>
  <div id="pledges" class="section">
  </div>


  <h1 class="section-label">국회활동</h1>
  <div id="politician-bill-activities" class="section">
  </div>

  <% if @vote_exists %>
  <h1 class="section-label">주요 이슈 표결</h1>
  <div id="politician-vote-activities" class="section">
  </div>
  <% end %>


  <div id="messages">
    <%= render :partial => 'message_form' %>
    <div id="messages_area_label">전체 한마디 <span id="total_message_count"><%= @messages.count %></span>개</div>
    <div id="messages_area">
      <%= render @messages %>
    </div>
  </div>
</div>