rails_app/config/routes.rb
Wepoll::Application.routes.draw do
  resources :timeline_entries do
    get 'blame', :on => :member
    get 'like', :on => :member
    get 'entry', :on => :member
  end

  resources :messages do 
		match '/list' => 'messages#list', :as => "list"
    post 'message_replies' => 'message_replies#create', :as => :replies
    get 'message_replies' => 'message_replies#index', :as => :replies
    get 'blame', :on => :member
    get 'like', :on => :member
  end

  resources :message_replies, :only => [:destroy]
  match "link_counts/:id" => "politicians#link_counts", :as => :link_counts_of_politician, :constraints => {:id => /[a-z0-9]+/}
  match "link_counts/:district" => "politicians#link_counts", :as => :link_counts_of_politician
  match 'timeline/:timeline_entry_id' => 'district#show_timeline_entry', :via => :get, :as => :display_timeline_entry
#  match "timeline_entries/list/:id" => "timeline_entries#list", :as => "timeline_entries_list"

  resources :bills
  resources :link_replies do
    match "/list" => "link_replies#list", :as => "list"
    get 'blame', :on => :member
    get 'like', :on => :member
  end
  resources :notices

  namespace :admin do
    match '/' => 'admin#index'
    match 'login' => 'auth#login'
    match 'logout' => 'auth#logout'
    match 'authorize' => 'auth#authorize'
    match 'new' => 'admin#new_admin', :via => :get
    match 'create' => 'admin#create_admin', :via => :post
    resources 'politicians' do
      get 'search', :as => 'search', :on => :collection
      post 'upload_photo', :as => 'upload_photo', :on => :collection
      get 'crawl_init_bills', :as => 'crawl_initiate_bill', :on => :member
    end
    resources 'bills' do
      get 'search', :as => 'search', :on => :collection
    end

    resources 'timeline_entries'
    resources 'users' do
      get 'suspend', :as => 'suspend', :on => :member
      post 'suspend_confirm', :as => 'suspend_confirm', :on => :member
      post 'suspend_cancel', :as => 'suspend_cancel', :on => :member
    end

    resources 'notices'
    resources 'link_replies'
    resources 'tweet_replies'
    resources 'tweets'
    resources 'pledges' do
      get 'search', :as => 'search', :on => :collection
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :sessions => "users/sessions"} do
    match 'users/sign_up/link_sns/:id' => 'users/registrations#link_sns', :via => :get, :as => 'new_user_link_sns'
    match '/auth_completed' => 'users/registrations#after_auth', :as => :after_auth
  end

  match 'users/auth/twitter/callback' => 'users/omniauth_callbacks#twitter'


  namespace :me do
    match 'sns/' => "sns#index"
    match 'sns/link/:provider' => "sns#link", :as => :sns_link
    match 'sns/mail_fail' => 'sns#mail_resend', :as => :sns_mail_resend

    match '/' => 'dashboard#index', :as => "dashboard"
  end
  match '/sns_verify/:user_id/:token_id/:key' => 'me/sns#verify_sns_link',
    :via => :get, :as => :sns_link_verify

  get 'forum/:tweet_name' => 'tweets#forum' , :as => :forum
  match '/get_tweet/:screen_name' => 'tweets#get_tweet', :as => :get_tweet

  resources :tweets do
    get 'like', :on => :member
    post 'tweet_replies' => 'tweet_replies#create', :as => :tweet_replies
    get 'tweet_replies' => 'tweet_replies#index', :as => :tweet_replies
  end
  resources :tweet_replies do
    get 'blame', :on => :member
    get 'like', :on => :member
    delete 'destroy', :on => :member
  end

  resources :pledges do
    get 'like', :on => :member, :as => :like
    get 'dislike', :on => :member, :as => :dislike
  end

  match '/fb_post_callback' => 'tweet_replies#fb_post_callback', :as => :fb_post_callback

  match 'district/:name/:p1_id/:p2_id' => 'district#show' ,:constraints => {:p1_id => /[a-z0-9]+/, :p2_id => /[a-z0-9]+/}, :as => :district_vs_politicians
  match 'district/:politician_id' => 'district#show' ,:constraints => {:politician_id => /[a-z0-9]+/}, :as => :district_politician
  match 'district/:name' => "district#show", :as => :district_name

  resources :politicians do
    get 'initiate_bills', :on => :member, :as => :init_bills_by
    get 'initiate_bills_summary',:on => :member, :as => :init_bills_summary_of
    get 'top_joint_initiate_bills',:on => :member, :as => :top_joint_initiate_bills_of
    get 'bill_activities', :on => :collection, :as => :bill_activities_of

    get 'popular_links', :on => :member, :as => :popular_links_of
    get 'recent_links', :on => :member, :as => :recent_links_of

    get 'popular_links_tab', :on => :collection, :as => :popular_links_tab_of
    get 'recent_links_tab', :on => :collection, :as => :recent_links_tab_of
    get 'votes_for_issues_tab', :on => :collection, :as => :votes_for_issues_tab_of

    get 'profile', :on => :collection, :as => :profiles_of
    get 'pledges', :on => :collection, :as => :pledges_of
    get 'messages_tab', :on => :collection, :as => :messages_tab_of

    get 'messages', :on => :collection, :as => :messages_of
  end

  match "/search" => "main#search"
match '/provision' => 'main#provision'
match '/privacy' => 'main#privacy'

  root :to => 'main#index'


  #for test
  match 'main/fb_test' => 'main#facebook_test', :as => :fb_test
  match 'main/fb_test_callback' => 'main#facebook_test_callback', :as => :fb_test_callback

  match 'main/tw_test' => 'main#twitter_test', :as => :tw_test
  match 'api/article_parse' => 'api#article_parsing'
  match 'api/youtube_parse' => 'api#youtube_parsing'
end

rails_app/app/models/message.rb
#coding: utf-8
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

	field :body, type: String
	field :tweet_feeed_id, type: String
	field :facebook_feed_id, type: String
  field :district, type: String
  field :like_count, type: Integer, default: 0
  field :blame_count, type: Integer, default: 0
	

	belongs_to :user
	belongs_to :preview

	belongs_to :politician
	belongs_to :pledge

	has_many :message_replies, :dependent => :destroy

  has_and_belongs_to_many :like_users, :class_name => "User", :inverse_of => :like_messages
  has_and_belongs_to_many :blame_users, :class_name => "User", :inverse_of => :blame_messages

  def posted_ago?
    ago = Time.now - created_at
    context = ""
    if (ago / 3600).to_i > 24
      context = ((ago / 3600) / 24).to_i.to_s + "일 전"
    elsif (ago / 3600).to_i > 0
      context = (ago / 3600).to_i.to_s + "시간 전"
    elsif (ago / 60) > 1
      context = (ago / 60).to_i.to_s + "분 전"
    else 
      context = "방금 전" 
    end
    context
  end

  def more_message?
    if replies.count > 3
      return true
    else
      return false
    end
  end

  def more_message
    replies.count - 3
  end

  def like(user)
    if self.like_users.include? user
      return false
    else
      self.like_count += 1
      self.like_users << user
      return self.save
    end
  end

  def blame(user)
    if self.blame_users.include? user
      return false
    else
      self.blame_count += 1
      self.blame_users << user
      return self.save
    end
  end
end

rails_app/app/controllers/messages_controller.rb
#coding: utf-8
class MessagesController < ApplicationController

	before_filter :authenticate_user!, :except => [:index, :new, :show]

  def list
    @entry = Message.find(params[:message_id])
    @replies = @entry.replies[0...@entry.replies.count - 3]
  end

	def index
		@messages = Message.all

	end

	def new
		@message = Message.new

	end

	def create
		@message = Message.new(params[:message])
    if params[:message][:politician_id] == "all"
      @message.politician_id = nil
      @message.politician = nil
    end
		@message.user_id = current_user.id
    @success = false

	
#		if params[:parent_message_id] != nil
#			@parent_message = Message.find(params[:parent_message_id])
#			@parent_message.replies << @message
#			@message.parent_message = @parent_message
#		end
		if @message.save
      @politician = @message.politician
      unless @politician.nil?
        @politician.inc(:message_count)
      end
      if params[:message][:tweet]
        @tweet = tweet_after_create
      end
      if params[:message][:facebook]
        @facebook = post_after_create
      end
      @success = true
		else
      @success = false
		end
	end

	def update

	end

	def show
		@message = Message.find(params[:id])

	end

	def destroy
    @message = Message.find(params[:id])
    @success = false
    @id = params[:id]
    if @message.user == current_user
      if @message.destroy
        @success = true
      else
        @success = false
      end
    else
      @success = false
    end
	end

  def like
    @message = Message.find(params[:id])
    if @message.like(current_user)
      render :json => {:status => "ok", :count => @message.like_count, :id => @message.id, :type => "like" }
    else
      render :json => {:status => "error", :message => "이미 추천하셨습니다."}
    end
  end
  def blame
    @message = Message.find(params[:id])
    if @message.blame(current_user)
      render :json => {:status => "ok", :count => @message.blame_count, :id => @message.id, :type => "blame" }
    else
      render :json => {:status => "error", :message => "이미 반대하셨습니다."}
    end
  end


  #begin protected

protected
  def tweet_after_create
    if current_user.twitter_token
      Twitter.configure do |config|
        config.consumer_key = TWITTER_CLIENT[:key]
        config.consumer_secret = TWITTER_CLIENT[:secret]
        config.oauth_token = current_user.twitter_token.access_token
        config.oauth_token_secret  = current_user.twitter_token.access_token_secret
      end

      begin
        if @politician.nil?
          path = district_name_path(message.district)
        else
          path = district_politician_path(@politician)
        end
        Twitter.update(params[:message][:body]+" http://wepoll.or.kr"+path+" \nhttp://wepoll.or.kr 에서 등록")
        true
      rescue Twitter::Error => e
        Rails.logger.info "Twitter tweet error"
        puts "Twitter tweet error"
        Rails.logger.info e.message
        puts e.message
        false
      end
    else
      Rails.logger.info "twitter token doesn't exist"
      puts "twitter token doesn't exist"
      false
    end
  end

  def post_after_create
    @facebook_cookies ||= Koala::Facebook::OAuth.new(FACEBOOK_CLIENT[:key], FACEBOOK_CLIENT[:secret]).get_user_info_from_cookie(cookies)
    unless @facebook_cookies.nil?
      begin
        @access_token = @facebook_cookies["access_token"]
        @graph = Koala::Facebook::GraphAPI.new(@access_token)
        if @politician.nil?
          path = district_name_path(@message.district)
          imgpath = "/btn_wepoll.gif"
          msg = "위폴에서 "+@message.district+"에 한마디를 등록하셨습니다." 
          Rails.logger.info "페이스북 포스팅중, 선거구는 #{@message.district} "
        else
          path = district_politician_path(@politician)
          imgpath = @politician.profile_photo.url(:square100)
          msg = "위폴에서 "+@message.district+" "+@politician.name+"에게 한마디를 등록하셨습니다."
          Rails.logger.info "페이스북 포스팅중, 정치인 이름은 #{@politician.name} "
        end
        Rails.logger.info imgpath
        Rails.logger.info "http://wepoll.or.kr"+imgpath
        @graph.put_object("me","feed",:message => params[:message][:body], :link => "http://wepoll.or.kr"+path, :picture => "http://wepoll.or.kr"+imgpath, :description => msg )
        true
      rescue StandardError => e
        Rails.logger.info "오류 발생"
        Rails.logger.info e.message
        puts e.message
      end
    else
      Rails.logger.info "facebook cookie doesn't exist"
      puts "facebook cookie doesn't exist"
      false
    end
  end

  ## end of protected

end

rails_app/app/helpers/messages_helper.rb
module MessagesHelper
  def url_maker(string)
    string.gsub(/(?<url>\b([\d\w\.\/\+\-\?\:]*)((ht|f)tp(s|)\:\/\/|[\d\d\d|\d\d]\.[\d\d\d|\d\d]\.|www\.|\.tv|\.ac|\.com|\.edu|\.gov|\.int|\.mil|\.net|\.org|\.biz|\.info|\.name|\.pro|\.museum|\.co)([\d\w\.\/\%\+\-\=\&amp;\?\:\\\&quot;\'\,\|\~\;]*)\b)/i,'<a href="http://\k<url>" target="_blank" class="url_in_box">\k<url></a>').gsub(/http\:\/\/http\:\/\//,'http://')
  end
end

rails_app/app/views/messages/_message.html.erb
<div class="message_entry message-entry-<%= message.id %> clearfix">
  <%= image_tag message.politician.profile_photo.url(:square100), :size => "40x40", :class => "message_politician_photo" unless message.politician.nil? %>
  <% if message.politician.nil? -%>
    <div class="message_politician_photo" style="color: red; text-align: center; width: 40px; height: 40px;">
      <%= message.district %>
    </div>
  <% end -%>
  <div class="message_entry_body clearfix">
    <%= message.user.nickname %>
    <span class="message_created_at"><%= message.created_at.strftime("%y.%m.%d %H:%M") %></span><br />

    <%= message.politician.nil? ? message.district : message.politician.name %> 후보에게<br />
    <%= url_maker(message.body).html_safe %>
  </div>
  <div class="message_entry_btns">
    <% if user_signed_in? -%>
      <%= link_to '추천', like_message_path(message), :class => "message_entry_btn like active" %><span class="like_count"><%= message.like_count %></span><br />
      <%= link_to '반대', blame_message_path(message), :class => "message_entry_btn blame active" %><span class="blame_count"><%= message.blame_count %></span>
    <% else -%>
      <%= link_to_function '추천', "show_login()", :class => "message_entry_btn like" %><span class="like_count"><%= message.like_count %></span><br />
      <%= link_to_function '반대', "show_login()", :class => "message_entry_btn blame" %><span class="blame_count"><%= message.blame_count %></span>
    <% end -%>
  </div>
  <%= link_to image_tag('/assets/admin/hr.gif'), message_path(message), :remote => true, :method => 'delete', :confirm => '삭제하시겠습니까?', :class => 'message_remove_btn' if current_user == message.user %>
  <% unless message.preview.nil? %>
    <div class="message_entries_preview preview clearfix">
      <img class="preview-img" src='<%= (message.preview and message.preview.image_url and message.preview.image_url.length>0) ? message.preview.image_url : "/assets/dummy-news-1.jpg" %>'>
      <div class="preview-right">
        <div class="preview-title"><a target="_blank" href="<%= raw message.preview.url if message.preview != nil%>"><%= message.preview.title if message.preview %></a></div>
        <div class="preview-link"><%= link_to message.preview.url[0..34] + "...", message.preview.url, :target => "_blank" %></div>
        <div class="preview-txt"><%= (s=message.preview.description;s.length > 120 ? s[0...117]+"...": s) if message.preview %></div>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>

  <p class="show_message_replies_btn"><%= link_to '덧글 ', message_replies_path(message), :remote => true %><span class="message_replies_count"><%= message.message_replies.count %></span></p>
  <div class="clear"></div>
  <div class="message_replies" style="display: none;">
    <div class="message_reply_form">
      <% if user_signed_in? -%>
        <%= form_tag message_replies_path(message), :remote => true do %>
          <%= text_field_tag 'message_reply[body]', nil, :class => "message_reply_txt_field", :placeholder => "한마디에 댓글을 적어주세요." %>
          <%= submit_tag '확인', :class => "message_reply_submit_btn" %>
        <% end %>
      <% else -%>
        <%= form_tag message_replies_path(message), :remote => true do %>
          <%= text_field_tag 'message_reply[body]', nil, :class => "message_reply_txt_field", :placeholder => "한마디에 댓글을 적어주세요.", :onclick => "show_login(); return false;" %>
          <%= submit_tag '확인', :class => "message_reply_submit_btn", :onclick => "show_login(); return false;" %>
        <% end %>
      <% end -%>
    </div>
    <ul class="message_replies_list">
    </ul>
  </div>
</div>

rails_app/app/views/messages/_message1.html.erb
<div class="message_entries message-entry-<%= message.id%> grid_10 alpha omega" data-id="<%=message.id %>" data-url="<%=raw message.preview.url if message.preview != nil %>">
  <%= image_tag (message.user ? message.user.profile_picture.url(:square50) : "/system/user_profile_pictures/anonymous_square50.gif"), :class => "message_profile_img", :size => "40x40" %>
  <p class="name"><%= message.user.nickname unless message.user.nil? %></p>
  <p class="politician"><%= message.politician.name %>후보에게 </p>
  <% if message.user == current_user -%>
    <%#= link_to image_tag('/assets/admin/hr.gif'), message_path(message), :method => 'delete', :confirm => '삭제하시겠습니까?', :class => "message_destroy_btn" %>
  <% end -%>
  <p class="message_body"> <%= message.body %> </p>

  <p class="time"><%= message.posted_ago? %></p>
  <% if message.preview != nil %>
    <div class="preview-wrap clearfix">
      <div class="preview-image"><img src='<%= (message.preview and message.preview.image_url and message.preview.image_url.length>0) ? message.preview.image_url : "/assets/dummy-news-1.jpg" %>'></div>
      <div class="preview-text">
        <div class="preview-title"><a target="_blank" href="<%= raw message.preview.url if message.preview != nil%>"><%= message.preview.title if message.preview %></a></div>
        <div class="preview-url"><%= link_to message.preview.url[0..34] + "...", message.preview.url, :target => "_blank" %></div>
        <div class="preview-desc"><%= (s=message.preview.description;s.length > 120 ? s[0...117]+"...": s) if message.preview %></div>
      </div>
    </div>
  <% end %>

  <div class="message_reply grid_9 alpha omega prefix_1">
    <% if message.more_message? %>
      <div class="message_more">
        <%= link_to "> #{message.more_message}개의 댓글 더 보기", message_list_path(message), :remote => true, :class => "grid_7 alpha omega", :style => "float: left;"%>
      </div>
    <% end %>

    <% message.replies.reverse[0..2].reverse.each do |r| %>
      <div class="message_replies clearfix <%= r.id %> grid_8 alpha omega">
        <% if r.user == current_user -%>
          <%= link_to image_tag('/assets/admin/hr.gif'), message_path(r), :method => 'delete', :confirm => '삭제하시겠습니까?', :remote => true, :class => "message_reply_destroy_btn" %>
        <% end -%>
        <%= image_tag (r.user ? r.user.profile_picture.url(:square50) : "/system/user_profile_pictures/anonymous_square50.gif"), :style => "float: left; margin-right: 10px;", :size => "40x40" %>
        <div class="message_replies_body">
          <p class="name"><%= (r.user ? r.user.nickname : "") %> <span class="date"><%= r.posted_ago? %></span></p>
          <% if r.preview != nil %>
            <div class="preview-wrap clearfix">
              <div class="preview-image"><img src='<%= (r.preview and r.preview.image_url and r.preview.image_url.length>0) ? message.preview.image_url : "/assets/dummy-news-1.jpg" %>'></div>
              <div class="preview-text">
                <div class="preview-title"><a target="_blank" href="<%= raw r.preview.url if r.preview != nil%>"><%= r.preview.title if r.preview %></a></div>
                <div class="preview-url"><%= link_to r.preview.url[0..34] + "...", r.preview.url, :target => "_blank" %></div>
                <div class="preview-desc"><%= (s=r.preview.description;s.length > 120 ? s[0...117]+"...": s) if r.preview %></div>
              </div>
            </div>
          <% end %>
          <p><%= r.body %></p>
        </div>
      </div>
    <% end %>
      
    <div class="message_reply_input alpha omega grid_9 clearfix">
      <form accept-charset="UTF-8" action="/messages" class="new_message" data-remote="true" id="new_message_<%=message.id.to_s%>" method="post">
        <div style="margin:0;padding:0;display:inline">
          <input name="utf8" type="hidden" value="✓">
          <input name="authenticity_token" type="hidden" value="4jEYDr9zpnQ9KDdKCut7jdg9/THK5PxITKnQZzGRZYI=">
        </div>     
        <%= hidden_field_tag 'parent_message_id', message.id.to_s %>
        <input id="message_preview_id_<%=message.id.to_s%>" name="message[preview_id]" type="hidden">
        <div class="reply_check">
          <span class="checkbox twitter"><input name="message[tweet]" type="checkbox" /></span>
          <span class="checkbox facebook"><input name="message[facebook]" type="checkbox" /></span>
          <span class="note">* 페이스북/트위터로 동시에 전송할 수 있습니다.</span>
        </div>

        <div class="clearfix">
          <% if user_signed_in? -%>
            <%= image_tag current_user.profile_picture.url(:square50), :size => "40x40" %>
          <% else -%>
            <%= image_tag '/system/user_profile_pictures/anonymous_square50.gif', :size => "40x40" %>
          <% end -%>

          <% if user_signed_in? -%>
            <textarea class="message_reply_write" cols="60" id="message_reply_write_<%=message.id.to_s%>" maxlength="140" name="message[body]" placeholder="댓글을 입력하세요." rows="5"></textarea>
          <% else -%>
            <a href="javascript:void(0)" onclick="show_login(); return false;"><textarea cols="60" disabled="disabled" id="message_body" name="message[body]" placeholder="로그인하면 댓글을 남길 수 있습니다." rows="5"></textarea></a>
          <% end -%>
        </div>
        <div class="clearfix">
          <div id="message-form-preview_<%=message.id%>" class="alpha omega field preview-wrap clearfix">
            <div id="message-form-preview-img_<%=message.id%>" class="preview-image"></div>
            <div id="message-form-preview-txt_<%=message.id%>" class="preview-desc"></div>
          </div>
        </div>

        <div style="float: right; margin-right:10px;">
          <div id="comment-length">
            <span class="current-comment-length">0</span>/250자
            <input class="message-reply-button" name="commit" type="submit" value="등록" onclick="message_reply_submit('<%=message.id.to_s%>'); return false;">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
$('.tooltip-top2').qtip()
$(function(){
	var loaded_url = '';
	$('.message_reply_write').keyup(function(event) {
		//console.log('key up event called!' + event.keyCode);
		// keyCode 32 = space 
		if (event.keyCode == 32) {
			var message_id = $(this).attr('id').split('_').pop();
			var str = $(this).val();
			var regex = /\b([\d\w\.\/\+\-\?\:]*)((ht|f)tp(s|)\:\/\/|[\d\d\d|\d\d]\.[\d\d\d|\d\d]\.|www\.|\.tv|\.ac|\.com|\.edu|\.gov|\.int|\.mil|\.net|\.org|\.biz|\.info|\.name|\.pro|\.museum|\.co)([\d\w\.\/\%\+\-\=\&amp;\?\:\\\&quot;\'\,\|\~\;]*)\b/gi;
			var url = str.match(regex);
			if (url != null && loaded_url != url) {
				loadUrlReply(url, message_id);
				loaded_url = url;
			}  
		}
	});

});


function message_reply_submit(id) {
		var data_string = $('#new_message_'+id).serialize();
		$.ajax({
			type: "POST",
			url: "/messages",
			data: data_string,
		});
}

function loadUrlReply(url, id)  {
	$.ajax({ url: '/api/article_parse', data: 'url='+encodeURIComponent(url), type: 'POST', dataType: 'json', success: 
		function(data)  { 
			$('#message_preview_id_'+id).val(data.id)
			if(data.image)  {
				$('#message-form-preview-img_'+id).html("<img class='grid_1' src='" + data.image + "'/>");
				$('#message-form-preview-txt_'+id).removeClass('prefix_1');
			}
			else
				$('#message-form-preview-txt_'+id).addClass('prefix_1');

			$('#message-form-preview-txt_'+id).html(data.title +  ' <br /> ' +data.description);
		} 
	}); 
};
</script>

rails_app/app/views/messages/_message_reply.html.erb
<div class="message_replies clearfix <%= message.id %> grid_8 alpha omega">
  <% if message.user == current_user -%>
    <%= link_to image_tag('/assets/admin/hr.gif'), message_path(message), :method => 'delete', :confirm => '삭제하시겠습니까?', :remote => true, :class => "message_reply_destroy_btn" %>
  <% end -%>
  <%= image_tag (message.user ? message.user.profile_picture.url(:square50) : "/system/user_profile_pictures/anonymous_square50.gif"), :style => "float: left; margin-right: 10px;", :size => "40x40" %>
  <div class="message_replies_body">
    <p class="name"><%= (message.user ? message.user.nickname : "") %> <span class="date"><%= message.posted_ago? %></span></p>
    <% if message.preview != nil %>
      <div class="preview-wrap clearfix">
        <div class="preview-image"><img src='<%= (message.preview and message.preview.image_url and message.preview.image_url.length>0) ? message.preview.image_url : "/assets/dummy-news-1.jpg" %>'></div>
        <div class="preview-text">
          <div class="preview-title"><a target="_blank" href="<%= raw message.preview.url if message.preview != nil%>"><%= message.preview.title if message.preview %></a></div>
          <div class="preview-url"><%= link_to message.preview.url[0..34] + "...", message.preview.url, :target => "_blank" %></div>
          <div class="preview-desc"><%= (s=message.preview.description;s.length > 120 ? s[0...117]+"...": s) if message.preview %></div>
        </div>
      </div>
    <% end %>
    <p><%= message.body %></p>
  </div>
</div>

rails_app/app/views/messages/create.js.erb
<% if @success -%>
  var total_cnt = $('#total_message_count').text()*1+1;
  $('#message-submit-btn').val('확인');
  $('#message-submit-btn').removeAttr('disabled');
  $('#total_message_count').text(total_cnt);
  $('#messages_area').prepend('<%= escape_javascript(render @message) %>');
  $('#message_body').val("");
  $('#message-body-length').text("0");
  $('#message_preview_id').val("");
  $('#message-form-preview img.preview-img').removeAttr('src');
  $('#message-form-preview-title').html("");
  $('#message-form-preview-link').html("");
  $('#message-form-preview-txt').html("");
  $('#message-form-preview').toggle();
  $('#message-body-container .comment').css('border-bottom','2px solid #9E9E9E');
  $('#message-form-preview').css('display', 'none');
  <% if @tweet == false -%>
    alert("트윗 전송에 실패했습니다.");
  <% end -%>
  <% if @facebook == false -%>
    alert("페이스북 전송에 실패했습니다.");
  <% end -%>
<% else -%>
  alert("한마디 작성에 실패했습니다.")
<% end -%>

rails_app/app/views/messages/destroy.js.erb
<% if @success -%>
  $('.message-entry-<%= @id %>').remove();
<% else -%>
  alert("한마디를 삭제하는데 실패했습니다.");
<% end -%>

rails_app/app/views/messages/list.html.erb
<% @replies.each do |r| %>
  <div class="message_replies clearfix <%= r.id %> grid_8 alpha omega">
    <% if r.user == current_user -%>
      <%= link_to image_tag('/assets/admin/hr.gif'), message_path(r), :method => 'delete', :confirm => '삭제하시겠습니까?', :remote => true, :class => "message_reply_destroy_btn" %>
    <% end -%>
    <%= image_tag (r.user ? r.user.profile_picture.url(:square50) : "/system/user_profile_pictures/anonymous_square50.gif"), :style => "float: left; margin-right: 10px;", :size => "40x40" %>
    <div class="message_replies_body">
      <p class="name"><%= r.user.nickname %> <span class="date"><%= r.posted_ago? %></span></p>
        <% if r.preview != nil %>
          <div class="preview-wrap clearfix">
            <div class="preview-image"><img src='<%= (r.preview and r.preview.image_url and r.preview.image_url.length>0) ? message.preview.image_url : "/assets/dummy-news-1.jpg" %>'></div>
            <div class="preview-text">
              <div class="preview-title"><a target="_blank" href="<%= raw r.preview.url if r.preview != nil%>"><%= r.preview.title if r.preview %></a></div>
              <div class="preview-url"><%= link_to r.preview.url[0..34] + "...", r.preview.url, :target => "_blank" %></div>
              <div class="preview-desc"><%= (s=r.preview.description;s.length > 120 ? s[0...117]+"...": s) if r.preview %></div>
            </div>
          </div>
        <% end %>
      <p><%= r.body %></p>
    </div>
  </div>
<% end %>

rails_app/app/views/messages/list.js.erb
$(".message-entry-<%= @entry.id %> .message_more").after("<%= escape_javascript render(:file => "messages/list.html.erb") %>");
$(".message-entry-<%= @entry.id %> .message_more").remove();