rails_app/config/routes.rb
Wepoll::Application.routes.draw do
  resources :timeline_entries do
    get 'blame', :on => :member
    get 'like', :on => :member
    get 'entry', :on => :member
  end

  resources :messages do 
		match '/list' => 'messages#list', :as => "list"
    post 'message_replies' => 'message_replies#create', :as => :replies
    get 'message_replies' => 'message_replies#index', :as => :replies
    get 'blame', :on => :member
    get 'like', :on => :member
  end

  resources :message_replies, :only => [:destroy]
  match "link_counts/:id" => "politicians#link_counts", :as => :link_counts_of_politician, :constraints => {:id => /[a-z0-9]+/}
  match "link_counts/:district" => "politicians#link_counts", :as => :link_counts_of_politician
  match 'timeline/:timeline_entry_id' => 'district#show_timeline_entry', :via => :get, :as => :display_timeline_entry
#  match "timeline_entries/list/:id" => "timeline_entries#list", :as => "timeline_entries_list"

  resources :bills
  resources :link_replies do
    match "/list" => "link_replies#list", :as => "list"
    get 'blame', :on => :member
    get 'like', :on => :member
  end
  resources :notices

  namespace :admin do
    match '/' => 'admin#index'
    match 'login' => 'auth#login'
    match 'logout' => 'auth#logout'
    match 'authorize' => 'auth#authorize'
    match 'new' => 'admin#new_admin', :via => :get
    match 'create' => 'admin#create_admin', :via => :post
    resources 'politicians' do
      get 'search', :as => 'search', :on => :collection
      post 'upload_photo', :as => 'upload_photo', :on => :collection
      get 'crawl_init_bills', :as => 'crawl_initiate_bill', :on => :member
    end
    resources 'bills' do
      get 'search', :as => 'search', :on => :collection
    end

    resources 'timeline_entries'
    resources 'users' do
      get 'suspend', :as => 'suspend', :on => :member
      post 'suspend_confirm', :as => 'suspend_confirm', :on => :member
      post 'suspend_cancel', :as => 'suspend_cancel', :on => :member
    end

    resources 'notices'
    resources 'link_replies'
    resources 'tweet_replies'
    resources 'tweets'
    resources 'pledges' do
      get 'search', :as => 'search', :on => :collection
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :sessions => "users/sessions"} do
    match 'users/sign_up/link_sns/:id' => 'users/registrations#link_sns', :via => :get, :as => 'new_user_link_sns'
    match '/auth_completed' => 'users/registrations#after_auth', :as => :after_auth
  end

  match 'users/auth/twitter/callback' => 'users/omniauth_callbacks#twitter'


  namespace :me do
    match 'sns/' => "sns#index"
    match 'sns/link/:provider' => "sns#link", :as => :sns_link
    match 'sns/mail_fail' => 'sns#mail_resend', :as => :sns_mail_resend

    match '/' => 'dashboard#index', :as => "dashboard"
  end
  match '/sns_verify/:user_id/:token_id/:key' => 'me/sns#verify_sns_link',
    :via => :get, :as => :sns_link_verify

  get 'forum/:tweet_name' => 'tweets#forum' , :as => :forum
  match '/get_tweet/:screen_name' => 'tweets#get_tweet', :as => :get_tweet

  resources :tweets do
    get 'like', :on => :member
    post 'tweet_replies' => 'tweet_replies#create', :as => :tweet_replies
    get 'tweet_replies' => 'tweet_replies#index', :as => :tweet_replies
  end
  resources :tweet_replies do
    get 'blame', :on => :member
    get 'like', :on => :member
    delete 'destroy', :on => :member
  end

  resources :pledges do
    get 'like', :on => :member, :as => :like
    get 'dislike', :on => :member, :as => :dislike
  end

  match '/fb_post_callback' => 'tweet_replies#fb_post_callback', :as => :fb_post_callback

  match 'district/:name/:p1_id/:p2_id' => 'district#show' ,:constraints => {:p1_id => /[a-z0-9]+/, :p2_id => /[a-z0-9]+/}, :as => :district_vs_politicians
  match 'district/:politician_id' => 'district#show' ,:constraints => {:politician_id => /[a-z0-9]+/}, :as => :district_politician
  match 'district/:name' => "district#show", :as => :district_name

  resources :politicians do
    get 'initiate_bills', :on => :member, :as => :init_bills_by
    get 'initiate_bills_summary',:on => :member, :as => :init_bills_summary_of
    get 'top_joint_initiate_bills',:on => :member, :as => :top_joint_initiate_bills_of
    get 'bill_activities', :on => :collection, :as => :bill_activities_of

    get 'popular_links', :on => :member, :as => :popular_links_of
    get 'recent_links', :on => :member, :as => :recent_links_of

    get 'popular_links_tab', :on => :collection, :as => :popular_links_tab_of
    get 'recent_links_tab', :on => :collection, :as => :recent_links_tab_of
    get 'votes_for_issues_tab', :on => :collection, :as => :votes_for_issues_tab_of

    get 'profile', :on => :collection, :as => :profiles_of
    get 'pledges', :on => :collection, :as => :pledges_of
    get 'messages_tab', :on => :collection, :as => :messages_tab_of

    get 'messages', :on => :collection, :as => :messages_of
  end

  match "/search" => "main#search"
match '/provision' => 'main#provision'
match '/privacy' => 'main#privacy'

  root :to => 'main#index'


  #for test
  match 'main/fb_test' => 'main#facebook_test', :as => :fb_test
  match 'main/fb_test_callback' => 'main#facebook_test_callback', :as => :fb_test_callback

  match 'main/tw_test' => 'main#twitter_test', :as => :tw_test
  match 'api/article_parse' => 'api#article_parsing'
  match 'api/youtube_parse' => 'api#youtube_parsing'
end

rails_app/app/controllers/admin/politicians_controller.rb
#coding: utf-8
require 'yaml'
class Admin::PoliticiansController < Admin::AdminController
  #XXX : for just debugging or external test connection
  #Be sure that remove this line for production
  skip_before_filter :is_admin?

  def index
    @politicians = Politician.page(params[:page]).per(20)

    respond_to do |format|
      format.html
      format.json do
#        render_options = {:json => {:data => @politicians, :pages => @politicians.page.num_pages , :current => @politicians.current_page }.to_json, :only => [:_id, :name]}
        if params[:callback]
          render :json => {:data => @politicians ,
            :pages => @politicians.page.num_pages,
            :current => @politicians.current_page}.to_json(:except => [:profile_photo_content_type, :profile_photo_file_name, :profile_photo_updated_at, :profile_photo_file_size, :bill_ids]), :callback => params[:callback]
        else
          render :json => {:data => @politicians,
            :pages => @politicians.page.num_pages,
            :current => @politicians.current_page}.to_json(:except => [:profile_photo_content_type, :profile_photo_file_name, :profile_photo_updated_at, :profile_photo_file_size, :bill_ids])
        end
      end
    end
  end

  def crawl_init_bills
    @politician = Politician.find(params[:id])
    @politician.crawl_init_bills
    redirect_to admin_politician_path(@politician)
  end

  def show
    @politician = Politician.find(params[:id])
    @keys = Politician.fields.keys.reject {|k| k.index("_") || k =~ /id$/}

    respond_to do |format|
      format.html
      format.json do
        if params[:callback]
          render :json => @politician, :callback => params[:callback]
        else
          render :json => @politician
        end
      end
    end
  end

  def new
    @politician = Politician.new
  end

  def edit
    @politician = Politician.find(params[:id])
  end

  def update
    params[:politician][:district] = "" if params[:politician][:district] == "없음"
    params[:politician][:elections] = params[:politician][:elections].split(",").map {|e| e.to_i}
    params[:politician][:promises] = YAML::load params[:promises]
    #XXX: eval은 위험
    params[:politician][:attendance] = eval params[:politician][:attendance]
    #XXX : elections가 확정적이 되면 이 필드는 필요없다
    params[:politician][:election_count] = params[:politician][:elections].count
    @politician = Politician.find(params[:id])

    if @politician.update_attributes(params[:politician])
      redirect_to admin_politician_path(@politician)
    else
      render edit_admin_politician_path(@politician)
    end
  end

  def create
    params[:politician][:district] = "" if params[:politician][:district] == "없음"
    params[:politician][:elections] = params[:politician][:elections].split(",").map {|e| e.to_i}
    params[:politician][:promises] = YAML::load params[:promises]
    #XXX: eval은 위험
    params[:politician][:attendance] = eval params[:politician][:attendance]
    #XXX : elections가 확정적이 되면 이 필드는 필요없다
    params[:politician][:election_count] = params[:politician][:elections].count
    @politician = Politician.new(params[:politician])

    if @politician.save
      redirect_to admin_politician_path(@politician)
    else
      render new_admin_politician_path
    end
  end

  def destroy
    @politician = Politician.find(params[:id])
    @politician.destroy
    redirect_to admin_politicians_path
  end

  def search
    @politicians = Politician.find(:all, :conditions => {:name => /#{params[:query]}/}).page(params[:page]).per(20)
    Rails.logger.info @politicians.count

    respond_to do |format|
      format.html {render :action => 'index'}
      format.js {render :json => @politicians.to_json(:only => [:_id, :name, :party])}
    end
  end

  def upload_photo
    tmp_file_name = (0...8).map{ ('a'..'z').to_a[rand(26)] }.join + "_" + Time.now.to_i.to_s
    #convert
    Rails.logger.info %x[convert #{params[:data].path} -format jpg #{Rails.root + "public/#{tmp_file_name}.jpg"}]
#    FileUtils.copy(params[:data].path, Rails.root + "public/" + tmp_file_name)
    FileUtils.copy(Paperclip::Thumbnail.new(File.open(Rails.root + "public/#{tmp_file_name}.jpg"), :geometry => params[:geometry], :format => 'jpg').make, Rails.root + "public/" + "#{tmp_file_name}_thumb.jpg")
File.open(Rails.root+"public/#{tmp_file_name}.jpg").chmod 0555
File.open(Rails.root+"public/#{tmp_file_name}_thumb.jpg").chmod 0555
    render :text => {:file_name => tmp_file_name+".jpg", :thumb_url => "/#{tmp_file_name}_thumb.jpg"}.to_json
  end
end

rails_app/app/controllers/politicians_controller.rb
#coding:utf-8
class PoliticiansController < ApplicationController

  before_filter :prepare_politicians, :except => [:initiate_bills, :popular_links, :recent_links]

  def initiate_bills
    @age = params[:age].to_i
    @politician = Politician.find(params[:id])
    if params[:result]
      @bills = @politician.initiate_bills.where(:result => '가결').where(:age => @age).page(params[:page]).per(8)
    else
      @bills = @politician.initiate_bills.page(params[:page]).where(:age => @age).per(8)
    end

    respond_to do |format|
      format.html do 
        @bill_categories = @politician.initiate_bills_categories(@age)
      end
      format.js {}
    end
    render :layout => false
  end

  def bill_activities
    @ages = @politicians.map {|p| p.elections.sort {|x,y| y<=>x}.first}
    c = -1
    bill_categories = @politicians.map {|p| p.initiate_bills_categories(@ages[c+=1])}

    @bill_counts = bill_categories.map {|bc| bc.map {|c,n| n}}
    @bill_categories = bill_categories.map {|bc| bc.map {|c,n| "#{c} #{n}"}}
    @party_color = {"자유선진" => "#007DC5", "통합진보" => "#6F0086", "무소속" =>"#4F4F50","진보신당" => "#f5314f", "민주통합" => "#257a01", "새누리당" => "#c2271e" }

    render :layout => false
  end

  def profile
    render :layout => false
  end

  def pledges
    @pledges = @politicians.map{|p| p.pledges.asc("_id")}
    @maxcount = @pledges.map {|c| c.count}.max
    render :layout => false
  end

  def recent_links_tab
    @entries = @politicians.map {|p| p ? p.timeline_entries.desc("created_at").page(params[:page]).per(3) : []}
    @link = LinkReply.new 
    render :layout => false
  end

  def popular_links_tab
    @entries = @politicians.map {|p| p ? p.timeline_entries.desc("like_count", "created_at").page(params[:page]).per(3) : []}
    @link = LinkReply.new 
    render :layout => false
  end

  def votes_for_issues_tab
    numbers = ["1803009","1803016","1804008","1803210","1803211","1804675","1803199","1803214","1802847","1807336","1806667","1807429","1807428","1806963","1807946","1810176","1808656","1809861","1810023","1806972","1807413","1811651","1811597","1811438","1812142","1801501","1812920","1813727","1814644","1814645"]
    @bills = Bill.where(:number.in => numbers).asc(:voted_at)
    @votes_by_politicians = VoteForBillByPolitician.any_in(:politician_id => [@politicians[0].id,@politicians[1].id])
    @votes_by_parties = VoteForBillByParty.asc(:party)

    render :layout => false, :file => 'politicians/issueline'
  end

  def messages_tab
  	 @p1 = params[:id1]
  	 @p2 = params[:id2]
     @messages = Message.where(:politician_id.in => [params[:id1],params[:id2]]).desc("created_at").page(params[:page]).per(10)
     @message = Message.new
     render :layout => false
  end

  def messages
     @messages = Message.where(:politician_id.in => [params[:id],params[:id2]]).desc("created_at").page(params[:page]).per(10)
     @message = Message.new
     render :layout => false
  end

  def recent_links
    @link = LinkReply.new 
    @p = Politician.find(params[:id])
    @entries = @p.timeline_entries.desc("created_at").page(params[:page]).per(3)
    render :layout => false
  end


  def popular_links
    @link = LinkReply.new 
    @p = Politician.find(params[:id])
    @entries = @p.timeline_entries.desc("like_count", "created_at").page(params[:page]).per(3)

    render :layout => false
  end

  def link_counts
    if params[:id]
      @pol = Politician.find(params[:id])
      render :json => {:good_link_count => @pol.good_link_count , :bad_link_count => @pol.bad_link_count}
    elsif params[:district]
      @pol = Politician.where(:district => params[:district])
      render :json => @pol.to_json(:only => [:_id, :good_link_count, :bad_link_count])
    end
  end

  def initiate_bills_summary
    @politician = Politician.find(params[:id])
    @party_color = {"자유선진" => "#007DC5", "통합진보" => "#6F0086", "무소속" =>"#4F4F50","진보신당" => "#f5314f", "민주통합" => "#257a01", "새누리당" => "#c2271e" }
    @age = params[:age].to_i
    bill_categories = @politician.initiate_bills_categories(@age)
    @index = params[:index].to_i
    @bill_counts = bill_categories.map {|c,n| n}
    @bill_categories = bill_categories.map {|c,n| "#{c} #{n}"}
    Rails.logger.info @bill_categories.to_json
    render :layout => false
  end



  def top_joint_initiate_bills
    @politician = Politician.find(params[:id])
    @top_joint_initiate_bill_politicians = @politician.joint_initiate_bill_politicians[params[:age].to_i][0...4]
    @bill_count = @politician.initiate_bills.where(:age => params[:age].to_i).count
    render :layout => false
  end

  protected
  def prepare_politicians
    @politicians = [params[:id1] ? Politician.find(params[:id1]) : nil, params[:id2] ? Politician.find(params[:id2]) : nil]
  end

end

rails_app/app/helpers/admin/politicians_helper.rb
module Admin::PoliticiansHelper
end

rails_app/app/helpers/politicians_helper.rb
module PoliticiansHelper
end

rails_app/app/views/admin/politicians/_form.html.erb
<% content_for :scripts do -%>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#politician_party").tokenInput(
        [{name:"민주통합"}, {name:"청년당"}, {name:"국민행복"}, {name:"새누리당"}, {name:"무소속"}, {name:"통합진보"}, {name:"국민생각"}, {name:"가자!대"}, {name:"국가재건"}, {name:"진보신당"}],
        //[{name:"민주통합"}, {name:"청년당"}, {name:"국민행복"}, {name:"새누리당"}, {name:"무소속"}, {name:"통합진보"}, {name:"국민생각"}, {name:"가자!대국민중심당"}, {name:"국가재건친박연합"}, {name:"진보신당"}],
        {
          tokenValue:"name",
          propertyToSearch:"name",
          tokenLimit:1,
          theme:'facebook'
        }
      );
      $("#politician_district").tokenInput(
        //TODO : 밑에 정리좀...ㅜㅜ
        [{name:"없음"}, {name:"종로"},{name:"용산"},{name:"성동갑"},{name:"성동을"},{name:"광진갑"},{name:"광진을"},{name:"동대문갑"},{name:"동대문을"},{name:"중랑갑"},{name:"중랑을"},{name:"성북갑"},{name:"성북을"},{name:"강북갑"},{name:"강북을"},{name:"도봉갑"},{name:"도봉을"},{name:"노원갑"},{name:"노원을"},{name:"노원병"},{name:"은평갑"},{name:"은평을"},{name:"서대문갑"},{name:"서대문을"},{name:"마포갑"},{name:"마포을"},{name:"양천갑"},{name:"양천을"},{name:"강서갑"},{name:"강서을"},{name:"구로갑"},{name:"구로을"},{name:"금천"},{name:"영등포갑"},{name:"영등포을"},{name:"동작갑"},{name:"동작을"},{name:"관악갑"},{name:"관악을"},{name:"서초갑"},{name:"서초을"},{name:"강남갑"},{name:"강남을"},{name:"송파갑"},{name:"송파을"},{name:"송파병"},{name:"강동갑"},{name:"강동을"},{name:"중구"},{name:"동구"},{name:"서구"},{name:"영도구"},{name:"부산진갑"},{name:"부산진을"},{name:"동래구"},{name:"남구갑"},{name:"남구을"},{name:"북구강서갑"},{name:"북구강서을"},{name:"해운대기장갑"},{name:"해운대기장을"},{name:"사하갑"},{name:"사하을"},{name:"금정구"},{name:"연제구"},{name:"수영구"},{name:"사상구"}],
        {
          tokenValue:"name",
          propertyToSearch:"name",
          tokenLimit:1,
          theme:'facebook'
        }
      );

      $("#politician_elections").tokenInput(
        [{age:"13"},{age:"14"},{age:"15"},{age:"16"},{age:"17"},{age:"18"},{age:"19"},{age:"20"}],
        {
          tokenValue:"age",
          propertyToSearch:"age",
          theme:'facebook'
        }
      );


      <% if @politician.district -%>
        $("#politician_district").tokenInput("add",
        {name:"<%= @politician.district %>"});
      <% end -%>

      <% if @politician.party -%>
        $("#politician_party").tokenInput("add",
        {name:"<%= @politician.party %>"});
      <% end -%>

      <% if @politician.elections -%>
        var elections = $.parseJSON('[<%=raw @politician.elections.map {|e| "{\"age\":#{e}}"}.join(",")%>]');
        for (var i in elections) {
          $("#politician_elections").tokenInput("add", elections[i]);
        }
      <% end -%>

      $("#politician_profile_photo").photoUpload({
        uploadAction:"<%= upload_photo_admin_politicians_path %>",
        imgWidth:100,
        imgHeight:100,
        placeholder_img_src:
        '<%= @politician.profile_photo? ? @politician.profile_photo.url(:square100) : "http://placehold.it/100x100"  %>',
        field_name:"data",
        optional_parameters:{geometry:"100x100#",authenticity_token:"<%= form_authenticity_token %>"}
      });

    });
  </script>
<% end -%>
<%= form_for [:admin, @politician] do |f| -%>
  <div class="table">
    <table class="listing form" cellpadding="0" cellspacing="0">
      <tr>
        <th class="full" colspan="2">정치인정보입력</th>
      </tr>
      <tr>
        <td><strong>이름</strong></td>
        <td><%= f.text_field :name %></td>
        <td rowspan="3"><%= f.file_field :profile_photo %></td>
      </tr>
      <tr>
        <td><strong>정당</strong></td>
        <td><%= f.text_field :party %></td>
      </tr>
      <tr>
        <td><strong>지역구</strong></td>
        <td><%= f.text_field :district %></td>
      </tr>
      <tr>
        <td><strong>생년월일</strong></td>
        <td colspan="2"><%= f.date_select :birthday, :start_year => 1930, :include_blank => true %></td>
      </tr>
      <tr>
        <td><strong>임기</strong></td>
        <td colspan="2"><%= f.text_field :elections %></td>
      </tr>
      <tr>
        <td><strong>트위터</strong></td>
        <td colspan="2">@<%=f.text_field :tweet_name %></td>
      </tr>
      <tr>
        <td><strong>병역</strong></td>
        <td colspan="2"><%= f.text_field :military%></td>
      </tr>
      <tr>
        <td><strong>공약</strong></td>
        <td colspan="2"><%= text_area_tag :promises, YAML::dump(@politician.promises)%></td>
      </tr>
      <tr>
        <td><strong>이력</strong></td>
        <td colspan="2"><%= f.text_area :experiences%></td>
      </tr>
      <tr>
        <td><strong>학력</strong></td>
        <td colspan="2"><%= f.text_area :education%></td>
      </tr>
      <tr>
        <td><strong>현직</strong></td>
        <td colspan="2"><%= f.text_field :job%></td>
      </tr>
      <tr>
        <td><strong>본회의출석률</strong></td>
        <td colspan="2"><%= f.text_field :attendance%></td>
      </tr>
      <tr>
        <td><strong>19대후보?</strong></td>
        <td colspan="2"><%= f.check_box :candidate%></td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= f.submit '확인'%>
  </div>
<% end -%>

rails_app/app/views/admin/politicians/edit.html.erb
<div class="top-bar">
  <h1>정치인 수정하기</h1>
</div>

<%= render :partial => 'form' %>

rails_app/app/views/admin/politicians/index.html.erb
<div class="top-bar">
  <h1>정치인 <small>(<%= Politician.count %>명)</small></h1>
</div>

<div class="select-bar">
  <%= form_tag search_admin_politicians_path, :method => 'get' do %>
    <%= text_field_tag 'query', params[:query], :placeholder => '이름입력' %>
    <%= submit_tag '검색' %>
  <% end-%>
</div>

<div class="table">
  <table class="listing" cellpadding="0" cellspacing="0">
    <tr>
      <th>이름</th>
      <th>생년월일</th>
      <th>지역구</th>
      <th>정당</th>
      <th>임기</th>
      <th>당선횟수</th>
    </tr>
    <% @politicians.each do |p| -%>
      <tr>
        <td><%= link_to p.name, admin_politician_path(p)%></td>
        <td><%= p.birthday%></td>
        <td><%= p.district%></td>
        <td><%= p.party%></td>
        <td><%= (p.elections||[]).join(",")%></td>
        <td><%= p.election_count%></td>
      </tr>
    <% end -%>
  </table>
</div>

<%= paginate @politicians%>

<div class="actions">
  <%= link_to '정치인 추가', new_admin_politician_path, :class => 'action add' -%>
</div>

rails_app/app/views/admin/politicians/new.html.erb
<div class="top-bar">
  <h1>정치인 추가하기</h1>
</div>

<%= render :partial => 'form' %>

rails_app/app/views/admin/politicians/show.html.erb
<div class="top-bar">
  <h1><%= @politician.name %></h1>
</div>

<div class="table">
  <table class="listing form" cellpadding="0" cellspacing="0">
    <tr><th colspan="2">정치인 정보</th></tr>
    <% @keys.each_with_index do |k, i| -%>
      <tr>
        <td><strong><%= k%></strong></td>
        <td style="text-align:left;"><%= v=(@politician.send k); v.class.to_s == 'Array' ? v.join(','): (k == 'experiences' ? simple_format(v) : v) %></td>
        <% if i == 0 -%>
          <td style="width:110px;" rowspan="<%=@keys.count+1%>"><%= image_tag @politician.profile_photo.url(:square100) if @politician.profile_photo? %></td>
        <% end -%>
      </tr>
    <% end -%>
    <tr>
      <td><strong>트위터</strong></td>
      <td style="text-align:left;"><%= @politician.tweet_name %></td>
    </tr>

    <tr>
      <td><strong>대표발의법안들</strong></td>
      <td colspan="2">
        <% @politician.initiate_bills.each do |b| -%>
          <%= link_to b.title, admin_bill_path(b) %><br />
        <% end -%>
      </td>
    </tr>

  </table>
</div>

<div class="actions">
  <%= link_to '대표법안생성' , crawl_initiate_bill_admin_politician_path(@politician), :class => 'action list', :confirm => '법안을 조회하고 데이터베이스에 집어넣기까지 오랜시간이 걸립니다. 계속 하시겠습니까?' %> | 
  <%= link_to '목록' , admin_politicians_path, :class => 'action list' %> | 
  <%= link_to '수정' , edit_admin_politician_path(@politician), :class => 'action edit' %> | 
  <%= link_to '삭제' , admin_politician_path(@politician), :method => 'delete', :confirm => '정말 삭제하시겠습니까?', :class => 'action destroy' %>
</div>