rails_app/config/routes.rb
Wepoll::Application.routes.draw do
  resources :timeline_entries do
    get 'blame', :on => :member
    get 'like', :on => :member
    get 'entry', :on => :member
  end

  resources :messages do 
		match '/list' => 'messages#list', :as => "list"
    post 'message_replies' => 'message_replies#create', :as => :replies
    get 'message_replies' => 'message_replies#index', :as => :replies
    get 'blame', :on => :member
    get 'like', :on => :member
  end

  resources :message_replies, :only => [:destroy]
  match "link_counts/:id" => "politicians#link_counts", :as => :link_counts_of_politician, :constraints => {:id => /[a-z0-9]+/}
  match "link_counts/:district" => "politicians#link_counts", :as => :link_counts_of_politician
  match 'timeline/:timeline_entry_id' => 'district#show_timeline_entry', :via => :get, :as => :display_timeline_entry
#  match "timeline_entries/list/:id" => "timeline_entries#list", :as => "timeline_entries_list"

  resources :bills
  resources :link_replies do
    match "/list" => "link_replies#list", :as => "list"
    get 'blame', :on => :member
    get 'like', :on => :member
  end
  resources :notices

  namespace :admin do
    match '/' => 'admin#index'
    match 'login' => 'auth#login'
    match 'logout' => 'auth#logout'
    match 'authorize' => 'auth#authorize'
    match 'new' => 'admin#new_admin', :via => :get
    match 'create' => 'admin#create_admin', :via => :post
    resources 'politicians' do
      get 'search', :as => 'search', :on => :collection
      post 'upload_photo', :as => 'upload_photo', :on => :collection
      get 'crawl_init_bills', :as => 'crawl_initiate_bill', :on => :member
    end
    resources 'bills' do
      get 'search', :as => 'search', :on => :collection
    end

    resources 'timeline_entries'
    resources 'users' do
      get 'suspend', :as => 'suspend', :on => :member
      post 'suspend_confirm', :as => 'suspend_confirm', :on => :member
      post 'suspend_cancel', :as => 'suspend_cancel', :on => :member
    end

    resources 'notices'
    resources 'link_replies'
    resources 'tweet_replies'
    resources 'tweets'
    resources 'pledges' do
      get 'search', :as => 'search', :on => :collection
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :sessions => "users/sessions"} do
    match 'users/sign_up/link_sns/:id' => 'users/registrations#link_sns', :via => :get, :as => 'new_user_link_sns'
    match '/auth_completed' => 'users/registrations#after_auth', :as => :after_auth
  end

  match 'users/auth/twitter/callback' => 'users/omniauth_callbacks#twitter'


  namespace :me do
    match 'sns/' => "sns#index"
    match 'sns/link/:provider' => "sns#link", :as => :sns_link
    match 'sns/mail_fail' => 'sns#mail_resend', :as => :sns_mail_resend

    match '/' => 'dashboard#index', :as => "dashboard"
  end
  match '/sns_verify/:user_id/:token_id/:key' => 'me/sns#verify_sns_link',
    :via => :get, :as => :sns_link_verify

  get 'forum/:tweet_name' => 'tweets#forum' , :as => :forum
  match '/get_tweet/:screen_name' => 'tweets#get_tweet', :as => :get_tweet

  resources :tweets do
    get 'like', :on => :member
    post 'tweet_replies' => 'tweet_replies#create', :as => :tweet_replies
    get 'tweet_replies' => 'tweet_replies#index', :as => :tweet_replies
  end
  resources :tweet_replies do
    get 'blame', :on => :member
    get 'like', :on => :member
    delete 'destroy', :on => :member
  end

  resources :pledges do
    get 'like', :on => :member, :as => :like
    get 'dislike', :on => :member, :as => :dislike
  end

  match '/fb_post_callback' => 'tweet_replies#fb_post_callback', :as => :fb_post_callback

  match 'district/:name/:p1_id/:p2_id' => 'district#show' ,:constraints => {:p1_id => /[a-z0-9]+/, :p2_id => /[a-z0-9]+/}, :as => :district_vs_politicians
  match 'district/:politician_id' => 'district#show' ,:constraints => {:politician_id => /[a-z0-9]+/}, :as => :district_politician
  match 'district/:name' => "district#show", :as => :district_name

  resources :politicians do
    get 'initiate_bills', :on => :member, :as => :init_bills_by
    get 'initiate_bills_summary',:on => :member, :as => :init_bills_summary_of
    get 'top_joint_initiate_bills',:on => :member, :as => :top_joint_initiate_bills_of
    get 'bill_activities', :on => :collection, :as => :bill_activities_of

    get 'popular_links', :on => :member, :as => :popular_links_of
    get 'recent_links', :on => :member, :as => :recent_links_of

    get 'popular_links_tab', :on => :collection, :as => :popular_links_tab_of
    get 'recent_links_tab', :on => :collection, :as => :recent_links_tab_of
    get 'votes_for_issues_tab', :on => :collection, :as => :votes_for_issues_tab_of

    get 'profile', :on => :collection, :as => :profiles_of
    get 'pledges', :on => :collection, :as => :pledges_of
    get 'messages_tab', :on => :collection, :as => :messages_tab_of

    get 'messages', :on => :collection, :as => :messages_of
  end

  match "/search" => "main#search"
match '/provision' => 'main#provision'
match '/privacy' => 'main#privacy'

  root :to => 'main#index'


  #for test
  match 'main/fb_test' => 'main#facebook_test', :as => :fb_test
  match 'main/fb_test_callback' => 'main#facebook_test_callback', :as => :fb_test_callback

  match 'main/tw_test' => 'main#twitter_test', :as => :tw_test
  match 'api/article_parse' => 'api#article_parsing'
  match 'api/youtube_parse' => 'api#youtube_parsing'
end

rails_app/app/models/bill.rb
#coding:utf-8
class Bill #법안모델
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes

  AGE = []
  AGE[0]  = [Date.parse("1948.5.31"),Date.parse("1950.5.30")]
  AGE[1]  = [Date.parse("1950.5.31"),Date.parse("1954.5.30")]
  AGE[2]  = [Date.parse("1954.5.31"),Date.parse("1958.5.30")]
  AGE[3]  = [Date.parse("1958.5.31"),Date.parse("1960.7.28")]
  AGE[4]  = [Date.parse("1960.7.29"),Date.parse("1961.5.16")]
  AGE[5]  = [Date.parse("1963.12.17"),Date.parse("1967.6.30")]
  AGE[6]  = [Date.parse("1967.7.1"),Date.parse("1971.6.30")]
  AGE[7]  = [Date.parse("1971.7.1"),Date.parse("1972.10.17")]
  AGE[8]  = [Date.parse("1973.3.12"),Date.parse("1979.3.11")]
  AGE[9]  = [Date.parse("1979.3.12"),Date.parse("1980.10.27")]
  AGE[10] = [Date.parse("1981.4.11"),Date.parse("1985.4.10")]
  AGE[11] = [Date.parse("1985.4.11"),Date.parse("1988.5.29")]
  AGE[12] = [Date.parse("1988.5.30"),Date.parse("1992.5.29")]
  AGE[13] = [Date.parse("1992.5.30"),Date.parse("1996.5.29")]
  AGE[14] = [Date.parse("1996.5.30"),Date.parse("2000.5.29")]
  AGE[15] = [Date.parse("2000.5.30"),Date.parse("2004.5.29")]
  AGE[16] = [Date.parse("2004.5.30"),Date.parse("2008.5.29")]
  AGE[17] = [Date.parse("2008.5.30"),Date.parse("2012.5.29")]


  #=== Mongoid fields ===
  field :title, type: String
  field :initiated_at, type: Date #발의일자
  field :voted_at, type: Date #표결일자
  field :complete, type: Boolean #표결여부 true : 의결, false : 계류
  field :result, type: String #표결결과
  field :commitee, type: String #소관위원회
  field :code, type: String #의안정보사이트 likms.assembly.go.kr 에서 쓰는 법안 코드
  field :number, type: Integer #국회에서 쓰이는 법안 번호
  field :summary, type: String
  field :tags, type: Array #comma separated된 값들
  field :age, type: Integer #언제 ''발의''된 법안인가?

  field :unregistered_coactor_names, type: Array #공동발의자이긴 한데 안잡힌 사람들
  #=== FOR DUPLICATE NAME ===
  field :duplicated_coactors_name, :type => Array, default: [] #공동발의자이긴 한데, 디비에 두명이상 존재하는 인간들

  #아래 값들은 타임라인 상에서 보이는건데, 이중 keyword는 tags에 포함될수도 있음.
  #개념정리가 좀 필요함
  field :keyword, type: String #issue 축약형
  field :issue, type: String #법안이 무슨 이슈에 관련된것인가? : ex) '출자총액제한 폐지', '사학법 개정'

  #=== Association ===
  belongs_to :initiator, class_name: "Politician", inverse_of: :initiate_bills #대표발의자
  has_and_belongs_to_many :coactors, class_name: "Politician" #공동발의자
  has_and_belongs_to_many :dissenters, class_name: "Politician",index: true #법안 반대자
  has_and_belongs_to_many :supporters, class_name: "Politician",index: true #법안 찬성자
  has_and_belongs_to_many :absentees, class_name: "Politician",index: true # 본회의 부재자
  has_and_belongs_to_many :attendees, class_name: "Politician",index: true # 표결 기권자

  belongs_to :vote
  attr_accessor :vs_votes

  def self.calculate_age
    Bill.all.each {|bill| bill.calculate_age}
  end

  def calculate_age
    update_attribute(:age, (AGE.find_index {|s,f| s <= initiated_at && initiated_at <= f })+1) if initiated_at
  end
end

rails_app/app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::AdminController
  #XXX : for just debugging or external test connection
  #Be sure that remove this line for production
#  skip_before_filter :is_admin?

  def index
    @bills = Bill.page(params[:page]).per(20)

    respond_to do |format|
      format.html
      format.json do
        if params[:callback]
          render :json =>  {:data => @bills,
           :pages => @bills.page.num_pages,
          :current => @bills.current_page}.to_json, :callback => params[:callback]
        else
          render :json =>  {:data => @bills,
           :pages => @bills.page.num_pages,
          :current => @bills.current_page}.to_json
        end
      end
    end
  end

  def show
    @bill = Bill.find(params[:id])
    @keys = Bill.fields.keys.reject {|k| k =~ /^_/ || k =~ /id[s]?$/ || k == 'summary'}

    respond_to do |format|
      format.html
      format.json do
        if params[:callback]
          render :json => @bill, :callback => params[:callback]
        else
          render :json => @bill
        end
      end
    end
  end

  def new
    @bill = Bill.new
  end

  def create
    params[:bill][:tags] = params[:bill_tags].split(",").map {|t| t.strip}.reject {|t| t.length == 0}
    params[:bill][:coactor_ids] = params[:bill][:coactor_ids].split(",")
    params[:bill][:supporter_ids] = params[:bill][:coactor_ids].split(",")
    params[:bill][:dissenter_ids] = params[:bill][:coactor_ids].split(",")
    @bill = Bill.new(params[:bill])

    if @bill.save
      redirect_to admin_bill_path(@bill)
    else
      render new_admin_bill_path
    end

  end

  def edit
    @bill = Bill.find(params[:id])
    @initiator = @bill.initiator
    @coactors = @bill.coactors
    @supporters = @bill.supporters
    @dissenters = @bill.dissenters
  end

  def update
    params[:bill][:tags] = params[:bill_tags].split(",").map {|t| t.strip}.reject {|t| t.length == 0}
    params[:bill][:coactor_ids] = params[:bill][:coactor_ids].split(",")
    params[:bill][:supporter_ids] = params[:bill][:coactor_ids].split(",")
    params[:bill][:dissenter_ids] = params[:bill][:coactor_ids].split(",")
    @bill = Bill.find(params[:id])
    if @bill.update_attributes(params[:bill])
      redirect_to admin_bill_path(@bill)
    else
      render edit_admin_bill_path(@bill)
    end
  end

  def search
    @bills = Bill.find(:all, :conditions => {:title => /#{params[:query]}/}).page(params[:page]).per(20)
    render :action => 'index'
  end
end

rails_app/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  layout false
 
 	# GET /bills
  # GET /bills.json
  def index
  	if params[:for_timeline]
			@bills = Bill.where(:initiator_id.in => params[:politicians]).where(:complete =>true).limit(10)
		else
	  	@bills = Bill.all.limit(10)
  	end

    respond_to do |format|
      format.json { render json: @bills.to_json(:include => {:initiator => {:only =>[:name]}}) }
    end

  end


	# GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])
	  respond_to do |format|
      format.json { render json: @bill}
      format.html 
    end
  end
end

rails_app/app/helpers/admin/bills_helper.rb
module Admin::BillsHelper
end

rails_app/app/helpers/bills_helper.rb
module BillsHelper
end

rails_app/app/views/admin/bills/_form.html.erb
<% content_for :scripts do -%>
  <script type="text/javascript">
    $(document).ready(function() {
      var coactors = $.parseJSON('<%=raw @coactors.to_json(:only => [:name, :_id, :party]) %>');
      var initiator = $.parseJSON('<%=raw @initiator.to_json(:only => [:name, :_id, :party]) %>');
      var dissenters = $.parseJSON('<%=raw @dissenters.to_json(:only => [:name, :_id, :party]) %>');
      var supporters = $.parseJSON('<%=raw @supporters.to_json(:only => [:name, :_id, :party]) %>');

      $(".politician-name").tokenInput(
        "<%= search_admin_politicians_path %>",
        {
          queryParam:"query", minChars:2,
          theme:'facebook',
          tokenValue:"_id",
          propertyToSearch:"_id",
          resultsFormatter:function(item) {
            return "<li>"+ item.name + "("+ item.party +")"+"</li>";
          },
          tokenFormatter:function(item) {
            return "<li><p>"+item.name+"</p></li>";
          }
        }
      );

      $("#bill_initiator_id").tokenInput("add", initiator);

      for (var i in coactors) {
        var o = coactors[i];
        $("#bill_coactor_ids").tokenInput("add", o);
      };

      for (var i in supporters) {
        var o = supporters[i];
        $("#bill_supporter_ids").tokenInput("add", o);
      };

      for (var i in dissenters) {
        var o = dissenters[i];
        $("#bill_dissenter_ids").tokenInput("add", o);
      };

    });
  </script>
<% end -%>
<%= form_for [:admin,@bill] do |f| -%>
  <div class="table">
    <table class="listing form" cellpadding="0" cellspacing="0">
      <tr>
        <th class="full" colspan="2">법안정보입력</th>
      </tr>
      <tr>
        <td><strong>법안명</strong></td>
        <td><%= f.text_field :title%></td>
      </tr>
      <tr>
        <td><strong>태그</strong></td>
        <td><%= text_field_tag :bill_tags, (@bill.tags || []).join(",")%></td>
      </tr>
      <tr>
        <td><strong>키워드</strong></td>
        <td><%= f.text_field :keyword%></td>
      </tr>
      <tr>
        <td><strong>이슈</strong></td>
        <td><%= f.text_field :issue%></td>
      </tr>
      <tr>
        <td><strong>발의일자</strong></td>
        <td><%= f.date_select :initiated_at%></td>
      </tr>
      <tr>
        <td><strong>표결일자</strong></td>
        <td><%= f.date_select :voted_at%></td>
      </tr>
      <tr>
        <td><strong>표결여부</strong></td>
        <td><%= f.select :complete, [["계류", false] , ["의결", true]]%></td>
      </tr>
      <tr>
        <td><strong>소관위원회</strong></td>
        <td><%= f.text_field :commitee%></td>
      </tr>
      <tr>
        <td><strong>법안코드</strong></td>
        <td><%= f.text_field :code%></td>
      </tr>
      <tr>
        <td><strong>법안번호</strong></td>
        <td><%= f.text_field :number%></td>
      </tr>
      <tr>
        <td colspan="2" class="full"><strong>주요내용</strong></td>
      </tr>
      <tr>
        <td colspan="2" class="full"><%= f.text_area :summary, :style => 'width:90%'%></td>
      </tr>
    </table>
  </div>

  <div class="table">
    <table class="listing form" cellpadding="0" cellspacing="0">
      <tr>
        <th class="full" colspan="2">의원정보입력</th>
      </tr>
      <tr>
        <td><strong>대표발의자</strong></td>
        <td><%= f.text_field :initiator_id, :class => 'politician-name' %>
      </tr>
      <tr>
        <td><strong>공동발의자</strong></td>
        <td><%= f.text_field :coactor_ids, :class => 'politician-name' %>
      </tr>
      <tr>
        <td><strong>찬성의원</strong></td>
        <td><%= f.text_field :supporter_ids, :class => 'politician-name' %>
      </tr>
      <tr>
        <td><strong>반대의원</strong></td>
        <td><%= f.text_field :dissenter_ids, :class => 'politician-name' %>
      </tr>

    </table>
  </div>

  <div class="actions">
    <%= submit_tag '확인' %>
  </div>
<% end -%>

rails_app/app/views/admin/bills/edit.html.erb
<div class="top-bar">
  <h1>법안 수정하기</h1>
</div>

<%= render :partial => 'form' %>

rails_app/app/views/admin/bills/index.html.erb
<div class="top-bar">
  <h1>법안 <small>(<%= Bill.count %>개)</small></h1>
</div>

<div class="select-bar">
  <%= form_tag search_admin_bills_path, :method => 'get' do %>
    <%= text_field_tag 'query', params[:query], :placeholder => '법안명입력' %>
    <%= submit_tag '검색' %>
  <% end-%>
</div>

<div class="table">
  <table class="listing" cellpadding="0" cellspacing="0">
    <tr>
      <th>제목</th>
      <th>대표발의</th>
      <th>처리여부</th>
      <th>처리결과</th>
      <th>발의일자</th>
      <th>처리일자</th>
    </tr>
    <% @bills.each do |b| -%>
      <tr>
        <td><%= link_to b.title, admin_bill_path(b)%></td>
        <td><%= b.initiator.name%></td>
        <td><%= b.complete ? "의결" : "계류"%></td>
        <td><%= b.result%></td>
        <td><%= b.initiated_at.strftime("%Y.%m.%d")%></td>
        <td><%= b.voted_at.strftime("%Y.%m.%d") unless b.voted_at.nil?%></td>
      </tr>
    <% end -%>
  </table>
</div>

<%= paginate @bills%>

<div class="actions">
  <%= link_to '법안 추가', new_admin_bill_path, :class => 'action add' -%>
</div>

rails_app/app/views/admin/bills/new.html.erb
<div class="top-bar">
  <h1>법안 추가하기</h1>
</div>

<%= render :partial => 'form' %>

rails_app/app/views/admin/bills/show.html.erb
<div class="top-bar">
  <h1><%= @bill.title %></h1>
</div>

<div class="table">
  <table class="listing form" cellpadding="0" cellspacing="0">
    <tr>
      <th colspan="2">법안정보</th>
    </tr>
    <% @keys.each do |k| -%>
      <tr>
        <td><strong><%= k%></strong></td>
        <td><%= @bill.send k %></td>
      </tr>
    <% end -%>

    <tr>
      <td><strong>발의의원</strong></td>
      <td><%= link_to @bill.initiator.name, admin_politician_path(@bill.initiator)%></td>
    </tr>

    <tr>
      <td><strong>공동발의자</strong></td>
      <td>
        <% @bill.coactors.each do |p2| -%>
          <%= link_to(p2.name, admin_politician_path(p2)) %>
        <% end -%>
      </td>
    </tr>

    <tr>
      <td><strong>주요내용</strong></td>
      <td>
        <%= simple_format @bill.summary %>
      </td>
    </tr>
  </table>
</div>

<div class="actions">
  <%= link_to '목록', admin_bills_path, :class => 'action list' %> | 
  <%= link_to '편집', edit_admin_bill_path(@bill), :class => 'action edit' %> | 
  <%= link_to '삭제', admin_bill_path(@bill), :method => :delete, :confirm => '정말 삭제하시겠습니까?', :class => 'action destroy' %>
</div>